lib/content.js, lib/route.js, test/example/md/test.md
Сheck the headers in the request
=> check headers

lib/setup.js
Fixed callback execution when callback has not been passed.
=> Fixed undefined callback call

lib/drakov.js
Error "cb() -> undefined is not a function" was fixed.
=> cb was missed

lib/content.js, lib/drakov.js, lib/request.js, test/api/delayed-response-test.js
* Add request delay option.
* Skip  _content-type_ header checks because it' s already checked.
=> Add request delay setting

lib/arguments.js, lib/request.js
Updated optimist options to output delay argument in help output when using in CLI.
Added a nice log to show how responses are being delayed.
=> Added delay to optimist and add log

CHANGELOG.md, README.md, lib/response.js, lib/route.js, package.json
TODO:
- Update dependencies
- Create list of contributors
- Better docs for contributors
- Add a changelog with contributor acknowlegdments
=> 0.1.0 version update

CHANGELOG.md, README.md, index.js, lib/content.js, lib/drakov.js, lib/middleware.js, lib/middleware/index.js, lib/middleware/request.js, lib/middleware/response.js, lib/middleware/route-handlers.js, lib/middleware/static.js, lib/route.js, lib/setup.js, package.json
Routes are now handled inside a single function for more flexible handling.
Will allow on the fly updating of route handling in the future.
Tidy up some logging.
=> Refactor route handling into single middleware module.

examples/node-module.js, lib/drakov.js, test/unit/drakov-test.js
Add unit tests.
Add example of using as node module.
=> Deal with running stop() when server is not started

lib/content.js, lib/json/meta-schema-v4.json, lib/route.js, lib/spec-schema.js, package.json, test/api/json-schema-test.js, test/example/md/json-schema.md, test/unit/spec-schema-test.js
Use JSON Schema to validate request body when schema is provided in specification.
=> Use JSON Schema to match request body

README.md, lib/arguments/arguments.js, lib/arguments/index.js, test/example/config/config.js
=> Add support for loading configuration from a file

lib/parse/blueprint.js, package.json, test/api/mson-api-test.js, test/example/md/mson-api.md
Although seems to be deprecated, [Drafter](https://github.com/apiaryio/drafter.js) seems to be the only current solution to have MSON support.
=> Drafter instead of Protagonist so we can parse MSON

.jshintrc, lib/middleware/route-handlers.js, lib/parse/url.js, lib/query-comparator.js, package.json, test/api/query-parameter-test.js, test/example/md/query-parameters.md, test/unit/query-comparator-test.js, test/unit/url-parser-test.js
This PR provides some work for #48 . There might still be some edge cases missing though.
PS: it's my first time working on a Node project so let me know if something doesn't fit.
=> Changed query params handling to accept query params matching

README.md, lib/arguments/index.js, package.json
Ran tests things seem to work fine...  First exposure to optimist and yargs, but it looks like the features used here are 1:1 port over for the api so was a trivial update.
=> Updating optimist

lib/content.js, lib/handler-filter.js, lib/middleware/route-handlers.js, lib/parse/action.js, lib/route.js, test/api/multipart-test.js, test/api/multiple-examples-api-test.js, test/example/md/form-urlencoded.md, test/example/md/headers.md, test/example/md/multiple-examples-api.md, test/example/md/simple-api.md, test/unit/content-test.js
This patch allows us to have multiple specs that has the same schema but different spec body.
=> Added support for multiple schema and body

lib/content.js, lib/middleware/endpoint-sorter.js, lib/middleware/route-map.js, test/api/static-versus-parametrized-api-test.js, test/example/md/static-versus-parametrized-api.md, test/unit/endpoint-sorter-test.js
Prioritize responses from static paths over parametric paths
Remove Content-Type header from headers matching
=> Prioritize responses from static paths over parametric paths

lib/content.js, test/api/multipart-test.js
Always match bodies when the request content type is multipart/form-data
=> Always match bodies when the request content type is multipart/form-data

Gruntfile.js, package.json, test/example/md/headers.md, test/example/md/multiple-examples-api.md, test/example/md/query-parameters.md, test/example/md/root-level-api.md, test/example/md/static-versus-parametrized-api.md
Add blueprint file validator to tests
=> Add blueprint file validator to tests

README.md, lib/arguments/arguments.js, lib/middleware/index.js, lib/middleware/response.js, test/api/headers-allow-headers-test.js
=> CORS - configurable Access-Control-Allow-Headers

package.json
No more dependencies using Protagonist.
=> Bump version and update depencencies

README.md, lib/arguments/arguments.js, lib/debugRequest.js, lib/drakov.js, test/api/debugger-test.js, test/unit/content-test.js
Requires  --debugMode on startup.
=> Add debug logs for mismatching requests

package-lock.json
Ensures everyone gets consistent versions, explicitly called out as a request during #186 by @vvscode
=> Issue #195 add the package-lock.json file to the repo
