Aconex/drakov

lib/route.js
Based on https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#uri-template-variable, it's necessary to ignore these operators to not break the express route.
With this change is possible to have:
```
/users{?page,limit,order}
/users?page=1{&limit,order}
/users/{id}{?page,limit,order}
```
Fix #8
=> #8 Ignore query and continuation operator for the route

Gruntfile.js, lib/drakov.js, lib/request.js, test/cors-test.js
- Enabled by default
- Pass disableCORS flag to disable it
- Included basic unit test for it
=> Added CORS header

lib/arguments.js, lib/drakov.js, lib/request.js, lib/response.js, test/api/headers-allow-methods-test.js, test/example/md/headers.md
Tidy up the request/response middleware modules.
Add support for a `Access-Control-Allow-Methods` header in the response.
=> Add option to add methods to Access-Control-Allow-Methods header

lib/content.js, lib/url-parser.js, test/api/multiple-examples-api-test.js, test/example/md/multiple-examples-api.md, test/unit/url-parser-test.js
In the current version of drakov if we send urlencoded form data, there were two problems with it.
- The request body for form-encoded post urls was not readable
In the md file we have to send data like this:-
+ Body 
`example=23&foo=bar`
which was not readable. So after our changes in the md file, the request body can be written like a normal   JSON:-
+ Body
`{
example: 23,
foor: bar
}`
- Issue with the request BODY when it is not in JSON format  
In file `content.js` there was check where we are equating the body of spec and http when the content type was not json, also  `/n`  was appended to the spec body automatically.
=>  Added functionality to support x-www--form-urlencoded content type.

lib/arguments.js, lib/setup.js
Adding an optional flag so users can open drakov up to external requests.
=> adding the "--public" flag to allow users to open the drakov server to

lib/content.js, test/api/multipart-test.js, test/example/md/multipart.md
For request containing multipart form data, browsers provide dynamic form boundary values (like `WebKitFormBoundaryjy0tIlk46ESOni0H`) which in turn change the content type (to something like `multipart/form-data; boundary=---WebKitFormBoundaryjy0tIlk46ESOni0H`)
Moreover, request body also can be different because of form boundary. 
Sample Request body:
------WebKitFormBoundaryjy0tIlk46ESOni0H
Content-Disposition: form-data; name="documentImportId"
undefined
------WebKitFormBoundaryjy0tIlk46ESOni0H
Content-Disposition: form-data; name="qquuid"
e3a2d2ed-0554-42c2-9629-3fad804547d8
------WebKitFormBoundaryjy0tIlk46ESOni0H
Content-Disposition: form-data; name="qqfilename"
tmprp8v07
------WebKitFormBoundaryjy0tIlk46ESOni0H
Content-Disposition: form-data; name="qqtotalfilesize"
-1 …
=> Added support for Multipart blueprint specifications

README.md, lib/content.js, lib/route.js, package.json, test/api/multiple-examples-api-test.js, test/example/md/multiple-examples-api.md
Hi,
As per the discussion in http://support.apiary.io/forums/120125-general/suggestions/3264498-match-on-request-headers, here is an implementation allowing to pick a response from the spec by preferred status code. Insanely useful when developing against an error prone API!
Kind regards,
@SiCurious and @kosmotaur from noths.com
=> support preferred status code as response

README.md, lib/arguments.js, lib/json/auto-options-action.json, lib/middleware/index.js, lib/middleware/response.js, lib/middleware/route-handlers.js, test/api/options-auto-response-test.js, test/example/md/simple-api.md
When creating server based on API blueprint I wanted to use AngularJS against drakov as a basic mocking server.
First I allowed CORS headers (including HEADERS for POST requests):
```
res.set('Access-Control-Allow-Origin', '*');
res.set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
```
After I would have to add OPTIONS action for every route so CORS prefight is successful.
Therefore I made slight changes to drakov to add OPTIONS action where it's missing. This is being turned on using flag `--autoOptions`
=> Automatically add OPTIONS action

lib/middleware/route-handlers.js, lib/middleware/route-map.js, lib/parse-action.js, lib/parse-blueprint.js
Hi,
While trying to introduce new functionalities, we've found it more difficult than it could be to reuse logic. The code was relying on side effects, functions were sharing variables through JS scope and modules were fulfilling more than one responsibility, which has proven to be a significant hindrance.
This came about when we were working on a discoverability page, where we wanted to list all the API endpoints. We needed to share the `ROUTE_MAP` object across modules, but unfortunately it was deeply entangled in other logic.
Please consider this refactor, where pieces of logic are contained as a function in separate modules, AKA the Substack pattern.
Starting with f004806, we've been extracting code step by step. Every commit after passed tests and retained Drakov's functionality, so …
=> Substack pattern

lib/content-type.js, lib/content.js, lib/url-parser.js, test/api/form-urlencoded-test.js, test/example/md/form-urlencoded.md, test/unit/url-parser-test.js
Continuation on Issue #46 
Relax `isBodyEqual` comparison for form-urlencoded requests.
Expected response will be sent if the body matches with the schema but on request body mentioned in the spec.
=> Add support for matching form-urlencoded http request body with schema mentioned in spec

lib/arguments/arguments.js, lib/drakov.js, lib/middleware/discover.js, package.json, test/api/discover-test.js, test/example/md/root-level-api.md, views/discover.jade, views/layout.jade
Hi!
We've created a basic discover page. The use case is, that if we serve the blueprints on our internal network, and people visit its URL, it has been voiced that they could very much use a listing of all the endpoints exposed.
It is a bit rudimentary, and we plan on utilising Aglio to make it a beaut, but didn't want to introduce a dependency that big into Drakov. That's why the `-D` option accepts a string value, which would be the module to require to build the middleware to handle the discover page. We'll build that module separately.
Kind regards,
@SiCurious and @kosmotaur
=> Discoverability

README.md
Just a proposal: I believe it is nice if the answer in the FAQ on "how to request specific response" includes a reference to the issue that discusses how to do it
=> FAQ Update: reference example how to request specific response

lib/drakov.js
Without this patch, I was getting the following error when navigating to /drakov in discover mode: `Error: Failed to lookup view "discover" in views directory "views"`. This resolves that error by calculating the proper absolute views path.
=> Use an absolute path for views

lib/middleware/response.js
In order that drakov supports credentialed requests there needs to be some tweaks to the control headers.
For example to use drakov together with the HAL browser this change is needed because the HAL browser can only send credentialed requests.
=> compatibility with credentialed requests

.travis.yml, lib/parse/blueprint.js, package.json, test/api/mson-api-test.js, test/example/md/mson-api.md
Created based on https://github.com/Aconex/drakov/pull/107
Used a newer version of travis image (https://docs.travis-ci.com/user/trusty-ci-environment/) that has by default g++ 4.8 needed for node 4 and 5
Added travis tests on node 4 and 5
=> Support newer versions of node

drakov, lib/arguments/arguments.js, lib/watcher.js, package.json
=> Shiny new file watcher with --watch argument

README.md, lib/arguments/index.js
Adding support for loading from `.drakovrc`
Will walk the path all the way until `/` is reached looking for a `.drakovrc` configuration file.
Referencing issue #112
=> Add support for automaticlly loading configuration file

.travis.yml, examples/express-middleware.js, lib/parse/blueprint.js, package.json
Once Protagonist is gone from Drakov and it's dependencies, there will be no more C compilation required during npm install. :+1:
=> Replace Protagonist with Drafter.js

README.md
Is the dependencies warning still needed with drafter.js?
=> Removed `Note on Dependencies` (no longer needed for drafter.js)

package.json
Looks like the latest compatible drafter.js version (2.4.3) is *much* faster at parsing API Blueprint files. Any chance you could bump a minor version and allow that update?
=> Allow drafter to upgrade to minor versions which are compatible with 2.x

Gruntfile.js, lib/content.js, lib/handler-filter.js, test/api/content-type-test.js, test/example/md/content-type.md, test/unit/content-test.js
This is an attempt to  make content-type matching less strict.
Refer to issue #136
=> Ignore content-type comparison when spec does not define it.

lib/content.js, lib/logger.js, lib/middleware/route-handlers.js, test/example/md/query-parameters.md, test/lib/stdout-hook.js, test/unit/content-test.js
Here is #139 PR, with resolved conflicts and added tests for logging diagnostic info.
Also I've refactored tests little bit, made them more readable by adding more context info.
This changes handle (and provide ability to debug) such kind of errors:
when request's path does not matched any documented endpoints
when request's headers does not matched headers schema for this endpoint
when request's body does not matched body schema (corresponding to request's content-type) for this endpoint
=> Log request matching process for better problem diagnosis #2

README.md, lib/arguments/arguments.js, lib/content.js, lib/handler-filter.js, lib/middleware/index.js, lib/middleware/route-handlers.js, test/api/debugger-test.js, test/api/headers-test.js, test/example/md/headers.md, test/unit/content-test.js
This change is to add the ability for Drakov to ignore user specified list of HTTP headers when it searches route handlers.
This feature could be useful if user has to put some headers in API blueprints (for example, for the sake of doing contract tests with Dredd), but don't want to strictly match these headers when Drakov is used as a mock server.
=> Adding support to ignore user specified HTTP headers when searching route handlers

examples/config.js
Adds explicit config file example directly in examples folder so that it's easier to find
=> Adds config file example

lib/arguments/arguments.js
Specifying `--ignoreHeader Authorization` once in the command line fails as the internal code is expecting an array. (https://github.com/Aconex/drakov/blob/master/lib/content.js#L114)
=> Set --ignoreHeader command line argument type as 'array'

.travis.yml, README.md
The README currently states that this package does not work on Node.js 7+, but using Node.js 8 on Linux, I'm not noticing any issue, and the test suite passes. The Travis CI build also passes with up to Node.js 8.
Let's trade this outdated statement for this Travis build.
=> Node 8 compatibility

lib/drakov.js, lib/setup.js, package.json
When I call the function `.stop()`, it only stops accepting new connections, it doesn't terminate existing connections. 
Because if `Connection: keep-alive` was requested by the client. It's an HTTP/1.1 feature to reduce the overhead of creating and tearing down a connection for each HTTP request.
=> Fix function drakov.stop dosen’t work

lib/parse/blueprint.js, test/api/simple-api-test.js, test/example/md/simple-api.md
The API blueprint [specification](https://apiblueprint.org/documentation/specification.html#def-action-section) defines an action as:
> Defined by an HTTP request method:
> 
> \<HTTP request method\>
> 
> -- or --
> 
> Defined by an action name (identifier) followed by an HTTP request method enclosed in square brackets [].
> 
> \<identifier\> [\<HTTP request method\>]
> 
> -- or --
> 
> Defined by an action name (identifier) followed by an HTTP request method and URI template enclosed in square brackets [].
> 
> \<identifier\> [\<HTTP request method\> \<URI template\>]
The last definition is not currently supported by Drakov as already mentioned in https://github.com/Aconex/drakov/issues/147. This PR fixes that.
=> Add ability to parse action url overrides 

lib/content.js
#192 
- arguments are read in as array only if there is multiple of those in the command
- if it is a string, place the string in an array instead
=> (ignoreHeaders) allow ignore single header. fixes #192

package.json
This change applies the latest suggestions from `npm audit fix` but with a force mode.  I run `npm test` locally after the change, and everything is still passing.
=> npm audit fix(FORCE) November 2020 
